image: docker:19.03.15

stages:
  - test
  - sonar
  - build_image
  - push_image
  - push_image_release
  - deploy_dev
  - deploy_qa
  - deploy_stg
  - deploy_prod

variables:
  SERVICE_NAME: monitor-service
  EKS_NAMESPACE: default
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

before_script:
  - export CONTAINER_IMAGE=$DEVOPS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$SERVICE_NAME
  - export VERSION=${CI_COMMIT_SHORT_SHA}
  - export RELEASE=$(echo ${CI_COMMIT_REF_NAME} | sed "s/\//_/g")
  - apk update && apk add bash
  - apk update && apk add openssl
  - apk update && apk add jq
  - export JSON_ASSUME_FILE_CI_CD=assume-role-ci-cd.json

Test:
  tags:
    - dale-devops-gitlab-runner
  stage: test
  allow_failure: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
  image: node:18-alpine
  script:
    - apk --no-cache add python3 py3-pip
    - pip3 install --no-cache-dir awscli
    - aws codeartifact login --tool npm --repository npm-private --domain avalsolucionesdigitales --domain-owner $DEVOPS_ACCOUNT_ID --region $AWS_DEFAULT_REGION
    - npm install
    - npm run test:cov
  artifacts:
    expire_in: 5 min
    paths: 
      - coverage/

sonarcloud-check:
  tags:
    - dale-devops-gitlab-runner
  stage: sonar
  allow_failure: true
  dependencies:
    - Test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner

build_image:
  tags:
    - dale-devops-gitlab-runner
  stage: build_image
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
          only_merge_request_event: "true"  
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ "/^fix/"
  script:
    - export AWS_ACCESS_KEY_ID=$(jq -r .AccessKeyId ${JSON_ASSUME_FILE})
    - export AWS_SECRET_ACCESS_KEY=$(jq -r .SecretAccessKey ${JSON_ASSUME_FILE})
    - export AWS_SESSION_TOKEN=$(jq -r .SessionToken ${JSON_ASSUME_FILE})
    - docker build -t $CONTAINER_IMAGE:$VERSION
      --build-arg DEVOPS_ACCOUNT_ID=$DEVOPS_ACCOUNT_ID
      --build-arg AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
      --no-cache .
    - docker tag $CONTAINER_IMAGE:$VERSION $CONTAINER_IMAGE:latest
    - >
      if [ "$only_merge_request_event" == "true" ]; then
        docker rmi $CONTAINER_IMAGE:$VERSION
      fi


push_image:
  tags:
    - dale-devops-gitlab-runner
  stage: push_image
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ "/^fix/"
  script:
    - docker push $CONTAINER_IMAGE:$VERSION
    - docker push $CONTAINER_IMAGE:latest
    - docker rmi $CONTAINER_IMAGE:$VERSION
    - docker rmi $CONTAINER_IMAGE:latest
    - echo TEMP1="${VERSION}" > $CI_PROJECT_DIR/variables.env
  artifacts:
    reports:
      dotenv: variables.env

push_image_release:
  tags:
    - dale-devops-gitlab-runner
  stage: push_image_release
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ "/^release/"
  script:
    - docker pull $CONTAINER_IMAGE:$VERSION
    - docker tag $CONTAINER_IMAGE:$VERSION $CONTAINER_IMAGE:$RELEASE
    - docker push $CONTAINER_IMAGE:$RELEASE
    - docker rmi $CONTAINER_IMAGE:$VERSION
    - docker rmi $CONTAINER_IMAGE:$RELEASE

deploy_dev_monitor:
  tags:
    - dale-devops-gitlab-runner
  stage: deploy_dev
  variables:
    APP_NAME: dale-dev-compute
    SECRET_PATH: monitor-service/secret_config-raToIm
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
  script:
    - if [ -z "$TEMP1" ]; then echo "VERSION is empty"; VERSION="latest"; fi
    - apk add --no-cache curl jq python3 py-pip
    - pip3 install awscli
    - bash .cicd/deploy-eks.sh dev $DEV_ACCOUNT_ID $AWS_DEFAULT_REGION $APP_NAME $EKS_NAMESPACE $SERVICE_NAME .cicd/helm $CONTAINER_IMAGE $VERSION $SECRET_PATH

deploy_qa_monitor:
  tags:
    - dale-devops-gitlab-runner
  stage: deploy_qa
  variables:
    APP_NAME: dale-qa-compute
    SECRET_PATH: monitor-service/secret_config-3Oae0t
  script:
    - echo "Deploy to qa server"
    - if [ -z "$TEMP1" ]; then echo "VERSION is empty"; VERSION="latest"; fi
    - apk add --no-cache curl jq python3 py-pip
    - pip3 install awscli
    - bash .cicd/deploy-eks.sh qa $QA_ACCOUNT_ID $AWS_DEFAULT_REGION $APP_NAME $EKS_NAMESPACE $SERVICE_NAME .cicd/helm $CONTAINER_IMAGE $CI_COMMIT_SHORT_SHA $SECRET_PATH
  environment:
    name: qa
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ "/^release/"

deploy_stg_monitor:
  tags:
    - dale-devops-gitlab-runner
  stage: deploy_stg
  variables:
    APP_NAME: dale-stg-compute
    SECRET_PATH: monitor-service/secret_config-WyrivH
  script:
    - echo "Deploy to stg server"
    - if [ -z "$TEMP1" ]; then echo "VERSION is empty"; VERSION="latest"; fi
    - apk add --no-cache curl jq python3 py-pip
    - pip3 install awscli
    - bash .cicd/deploy-eks.sh stg $STG_ACCOUNT_ID $AWS_DEFAULT_REGION $APP_NAME $EKS_NAMESPACE $SERVICE_NAME .cicd/helm $CONTAINER_IMAGE $CI_COMMIT_SHORT_SHA $SECRET_PATH
  environment:
    name: stg
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ "/^release/"

deploy_prod_monitor:
  tags:
    - dale-devops-gitlab-runner
  stage: deploy_prod
  variables:
    APP_NAME: dale-prod-compute
    SECRET_PATH: monitor-service/secret_config-wWP3v9
  script:
    - echo "Deploy to prod server"
    - if [ -z "$TEMP1" ]; then echo "VERSION is empty"; VERSION="latest"; fi
    - apk add --no-cache curl jq python3 py-pip
    - pip3 install awscli
    - bash .cicd/deploy-eks.sh prod $PROD_ACCOUNT_ID $AWS_DEFAULT_REGION $APP_NAME $EKS_NAMESPACE $SERVICE_NAME .cicd/helm $CONTAINER_IMAGE $CI_COMMIT_SHORT_SHA $SECRET_PATH
  environment:
    name: prod
  when: manual
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ "/^release/"
