version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_USER: ${TYPEORM_BACKOFFICE_USERNAME}
      POSTGRES_PASSWORD: ${TYPEORM_USER_PASSWORD}
      POSTGRES_DB: ${TYPEORM_BACKOFFICE_DATABASE}
    container_name: backoffice-ms
    # volumes: 
    # - ./postgres:/var/lib/postgresql/data
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: spryker/redis-commander:0.8.0
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis