process.env.EVENT_LOG_VERSION = '3.0';
process.env.EVENT_LOG_MNEMONIC = 'TRFINTRCR';
process.env.EVENT_LOG_DEBITCODE = 100;
process.env.EVENT_LOG_CREDITCODE = 102;
process.env.EVENT_LOG_DEBITNAME = 'MONEY_TRANSFER_CORE';
process.env.EVENT_LOG_CREDITNAME = 'RECEIVE_TRANSFER_CORE';

process.env.EVENT_LOG_APPLICATION = 'DALE 2.0';
process.env.EVENT_LOG_CHANNEL = 'PTS INTEGRADOR';
process.env.SASL_USERNAME = 'dev-msk-user';
process.env.KAFKA_RETRIES = 1;

process.env.CASHIN_PSE_EVENT_LOG_MNEMONIC = 'PSETRNLD';
process.env.CASHIN_PSE_EVENT_LOG_CODE = 1005;
process.env.CASHIN_PSE_EVENT_LOG_NAME = 'MONEY_LOADUP_CORE';
