export const functionalities = {
  SERVICE_CONFIGURATION: 'SERVICE_CONFIGURATION',
  CREATE_USER: 'CREATE_USER',
  GET_USER_DATA: 'GET_USER_DATA',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_PHONE_NUMBER: 'UPDATE_PHONE_NUMBER',
};

export const functionalitiesFavorites = {
  CREATE__FAVORITE_USER: 'CREATE__FAVORITE_USER',
  GET_FAVORITE_USER: 'GET_FAVORITE_USER',
  DELETE_FAVORITE_USER: 'DELETE_FAVORITE_USER',
};

export enum EnrollmentStatusEnum {
  APPROVED = 'APPROVED',
  REJECT = 'REJECT',
}
