apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: {{ include "account-service.fullname" . }}
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  region: us-east-1
  data:
{{- range .Values.secret.name }}
    - key: {{ $.Values.secret.path }}
      name: {{ . }}
      property: {{ . }}
{{- end }}  
    
