apiVersion: v1
kind: Service
metadata:
  name: {{ include "account-service.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: dev.dale2.0.internal
  labels:
    {{- include "account-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "account-service.selectorLabels" . | nindent 4 }}
