export enum clientStateEnum {
  ACTIVO = 'ACTIVO',
  INACTIVO = 'INACTIVO',
  CONGELADO = 'CONGELADO',
  EMBARGADO = 'EMBARGADO',
  CANCELADO = 'CANCELADO',
  BLOQUEADO = 'BLOQUEADO',
  MIGRADO = 'MIGRADO',
  EMPTY = '',
}
