# Default values for product-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  pullPolicy: Always

env:
  NODE_ENV: 'production'
  SERVICE_TYPE: 'api'
  SERVICE_NAME: 'monitor-service'
  MONITOR_SERVICE_PORT: 3000
  CLOUD_SERVICE_PROVIDER: 'AWS'
  AWS_REGION: 'us-east-1'
  AWS_XRAY_DAEMON_ADDRESS: 'xray-service.default:2000'
  ENABLE_AUDIT: 'false'
  REDIS_TLS_ENABLED: 'true'
  NODE_EXTRA_CA_CERTS: 'src/certchain/ca-certificate-chain.pem'
  KAFKA_SSL_ENABLED: 'true'
  ENROLLMENT_NP_SERVICE_URL: 'https://enrollment-np-service.default.svc.cluster.local:5016'
  USER_SERVICE_URL: 'https://user-service.default.svc.cluster.local:5003'
  CONFIGURATION_SERVICE_URL: 'https://configuration-service.default.svc.cluster.local:5014'
  REDIS_TTL: 43200
  KAFKA_RETRIES: 0
  EVENT_LOG_VERSION: '3.0'
  EVENT_LOG_MNEMONIC: 'TRFINTRCR'
  EVENT_LOG_DEBITCODE: '100'
  EVENT_LOG_CREDITCODE: '101'
  EVENT_LOG_DEBITNAME: 'MONEY_TRANSFER_CORE'
  EVENT_LOG_CREDITNAME: 'RECEIVE_TRANSFER_CORE'
  EVENT_LOG_APPLICATION: 'DALE 2.0'
  EVENT_LOG_CHANNEL: 'PTS INTEGRADOR'
  KAFKA_SSL_ENABLED_PTS: true
  KAFKA_RETRY_POLICY_PTS: 4
  KAFKA_RETRY_POLICY: 4
  AWS_XRAY_CONTEXT_MISSING: 'LOG_ERROR'
  AWS_XRAY_LOG_LEVEL: 'error'
  CARD_SERVICE_URL: 'https://card-service.default.svc.cluster.local:5015'
  

secret:
  path:
  name:
    - CERTIFICATE_CHAIN
    - CERTIFICATE_PRIVATE_KEY
    - PUBLIC_CERTIFICATE
    - REDIS_AUTH_TOKEN
    - REDIS_HOST
    - REDIS_PORT
    - KAFKA_URLS
    - SASL_USERNAME
    - SASL_PASSWORD
    - KAFKA_URLS_PTS
    - KAFKA_TOPIC_PTS
    - SASL_USERNAME_PTS
    - SASL_PASSWORD_PTS
    - CRM_SERVICE_URL
    - CRM_USERNAME
    - CRM_PASSWORD
    - SQS_TRANSACTION_LOG
    - SQS_URL
    - SECRET_ID_GENERATE_KEY_SYMETRIC_AUDMON
    - SECRET_PATH_GENERATE_KEY_SYMETRIC_AUDMON



imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: 'monitor-service'
  # Annotations to add to the service account
  annotations:
    required: 'true'

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 5020
  targetPort: 3000

ingress:
  enabled: false
  className: ''
  annotations: {}
  tls: []

resources:
  limits:
    cpu: 256m
    memory: 512Mi
  requests:
    cpu: 128m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []
affinity: {}
