export const functionalities = {
  CREATE_ACCOUNT: 'CREATE_ACCOUNT',
  GET_ACCOUNT_DETAILS_BY_CLIENT_ID: 'GET_ACCOUNT_DETAILS_BY_CLIENT_ID',
  GET_ACCOUNT_DETAILS_BY_ACCOUNT_ID: 'GET_ACCOUNT_DETAILS_BY_ACCOUNT_ID',
  GET_ACCOUNT_NUMBERS_BY_CLIENT_ID: 'GET_ACCOUNT_NUMBERS_BY_CLIENT_ID',
  GET_ACCOUNT_LIMITS_BY_CLIENT_ID: 'GET_ACCOUNT_LIMITS_BY_CLIENT_ID',
  GET_CONSULT_THE_ELECTRONIC_DEPOSIT: 'GET_CONSULT_THE_ELECTRONIC_DEPOSIT',
};
