export const ColumsRegistrer = [
  { header: 'Código de Transacción', key: 'transactionCode', width: 10 },
  { header: 'Nombre de Transacción', key: 'transactionDescription', width: 20 },
  { header: 'Tipo de Ajuste', key: 'adjustmentType', width: 20 },
  { header: 'Valor', key: 'amount', width: 20 },
  { header: 'Número de depósito', key: 'depositNumber', width: 20 },
  { header: 'Usuario capturador', key: 'captureruser', width: 20 },
  { header: 'Fecha captura', key: 'dateCapturer', width: 10 },
  { header: 'Usuario verificador', key: 'verifierUser', width: 10 },
  { header: 'Fecha de verificacón', key: 'dateVerified', width: 10 },
  { header: 'Usuario aprobador', key: 'approverUser', width: 30 },
  { header: 'Fecha de aprobación', key: 'dateApproved', width: 30 },
  { header: 'Estado de ajuste', key: 'adjustmentState', width: 30 },
  { header: 'Motivo de rechazo', key: 'comment', width: 30 },
];
